baseurl = "/"
languageCode = "en-us"
title = "Henrik's blog"
theme = "hugo-xmin"
googleAnalytics = "UA-155259274-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "â†©"
enableRobotsTXT = true

[permalinks]
    post = "/post/:slug/"
    note = "/note/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Blog posts"
    url = "/post/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A bunch of not always well considered notes"
    footer = "&copy; [Henrik Lindberg](https://blog.k2h.se) | [Github](https://github.com/halhen) | [Twitter](https://twitter.com/hnrklndbrg)"